backbone: naver-clova-ocr/bros-base-uncased
word_embeddings: vinai/phobert-base
head_dims: 256

# For continue training
pretrained_weights: null

# For inference
inference_weights: null

num_special_classes: 3
classes:
  - barcode
  - date
  - customer
  - agency
  - representative
  - address
  - id
  - booknum
  - declnum
  - unit
  - quantity
  - tweight
  - kweight
  - signname
